spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      format_sql: true
      default_batch_fetch_size: 20
      # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
      jdbc.batch_size: 20
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
#    localhost:8080/h2-console
#    tcp: jdbc:h2:tcp://localhost:9092/mem:test