spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.1.157:5431/deposit_service_database
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    port: 5672
    host: rabbitmq
#    host: localhost
#    host: 192.168.1.157
    username: guest
    password: guest
    listener:
      direct:
        default-requeue-rejected: true

server:
  port: 8079