spring:
  cloud:
    gateway:
      routes:
        - id: account-service
#          uri: http://localhost:8081
          uri: lb://account-service
          predicates:
            - Path=/accounts/**

        - id: bill-service
#          uri: http://localhost:8082
          uri: lb://bill-service
          predicates:
            - Path=/bills/**

        - id: deposit-service
          uri: lb://deposit-service
#          uri: http://localhost:8080
          predicates:
            - Path=/deposits/**
server:
  port: 8989