server:
  port: 9999

spring:
  rabbitmq:
    port: 5672
#    host: rabbitmq
#    host: localhost
    host: 192.168.1.157
    username: guest
    password: guest
    listener:
      direct:
        default-requeue-rejected: true