server:
  port: 9999

spring:
  rabbitmq:
    port: 5672
#    host: rabbitmq
    host: localhost
    username: guest
    password: guest
    listener:
      direct:
        default-requeue-rejected: true