spring:
  config:
    import: configserver:http://config-service:8001/
  application:
    name: registry
  cloud:
    config:
      uri: http://config-service:8001
#      uri: http://192.168.1.157:8001
      fail-fast: true
      password: admin
      username: user


eureka:
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
  server:
    peer-node-read-timeout-ms: 100000